# Lightweight Image
FROM golang:1.25-alpine AS builder

WORKDIR /app
COPY go.mod ./.
COPY go.sum ./.
RUN go mod download


#COPY everything else
COPY . .

RUN go build -o server ./cmd/server/natsMain.go

#Stage-2, Multi-Stage Build
FROM alpine:latest

WORKDIR /root/
#Binary Code of the Running Executed Server.
COPY --from=builder /app/server .

EXPOSE 8081

CMD ["./server"]


#curl -X POST http://localhost:8080/route -d '{"start_x":0, "start_y":0, "end_x":2, "end_y":2}'#
#Example Command for CLI