version: '3.8'

services:
  
  api:
    # Build the Dockerfile in the current directory (.)
    build: .
    depends_on: [nats]
    
    ports:
      - "8081:8081"
    
    environment:
      - ENV=production
    
    restart: on-failure
  nats:
    image: nats:latest
    command: "-js -store_dir /data" #js-> jetstream, -store_dir -> storage directory
    ports:
      - "4222:4222" #client
      - "8222:8222" #dashboard
  
  #CLI Tool
  toolbox:
    image: natsio/nats-box:latest
    command: sleep infinity
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats