# Lightweight Image
FROM golang:1.25-alpine AS Builder

WORKDIR /app
COPY go.mod ./.
#Add COPY go.sum ./. as no external dependecies, will add when configuring NATS
RUN go mod download


#COPY everything else
COPY . .

RUN go build -o server ./cmd/server/main.go

#Stage-2, Multi-Stage Build
FROM alpine:latest

WORKDIR /root/
#Binary Code of the Running Executed Server.
COPY --from=builder /app/server .

EXPOSE 8080

CMD ["./server"]


#curl -X POST http://localhost:8080/route -d '{"start_x":0, "start_y":0, "end_x":2, "end_y":2}'#
#Example Command for CLI